"""add category and product

Revision ID: 3cf7147640e6
Revises: 
Create Date: 2025-12-13 20:41:29.878812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf7147640e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.UniqueConstraint('name', name='uq_category_name')
    )

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('category', sa.Enum('news', 'publication', 'tech', 'other', 'life', name='postcategory'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('author', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
    'product',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
        ['category_id'],
        ['category.id'],
        name='fk_product_category'
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('post')
    op.drop_table('category')
    # ### end Alembic commands ###
